# Generated by Django 5.2.13 on 2026-05-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100)),
                ('event', models.CharField(choices=[('order.created', 'Order Created'), ('payment.captured', 'Payment Captured'), ('payment.failed', 'Payment Failed'), ('payment.refunded', 'Payment Refunded'), ('signature.verified', 'Signature Verified'), ('signature.failed', 'Signature Failed'), ('webhook.received', 'Webhook Received'), ('webhook.ignored', 'Webhook Ignored')], max_length=40)),
                ('source', models.CharField(choices=[('client', 'Client Callback'), ('webhook', 'Razorpay Webhook'), ('manual', 'Manual / Admin')], default='client', max_length=20)),
                ('amount_paise', models.PositiveIntegerField(default=0, help_text='Amount in paise (100 paise = ₹1)')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('success', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_description', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='Null if order could not be resolved (e.g. unknown rzp_order_id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
