# Generated by Django 5.2.13 on 2026-05-04 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=100)),
                ('uses_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, choices=[('leaf', '🌿 Leaf'), ('pot', '🪴 Pot'), ('seedling', '🌱 Seedling'), ('spray', '💧 Spray'), ('tag', '🏷️ Offers'), ('bundle', '📦 Bundle'), ('truck', '🚚 Bulk')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Main Category (Navbar)',
                'verbose_name_plural': 'Main Categories (Navbar)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('whatsapp_number', models.CharField(default='919XXXXXXXXXX', help_text='Include country code, no + sign. e.g. 919876543210', max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='SpaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name e.g. 'sofa', 'bed', 'sun'", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/')),
                ('is_featured', models.BooleanField(default=False, help_text="Show in 'Curate your atmosphere' on homepage")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Show in 'Explore by Category' on homepage")),
                ('order', models.PositiveIntegerField(default=0)),
                ('main_category', models.ForeignKey(help_text='Which top-level section does this belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.maincategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(help_text='e.g. PLT-001, PLN-002', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='MRP / crossed-out price', max_digits=10, null=True)),
                ('care_level', models.CharField(blank=True, choices=[('easy', 'Easy Care'), ('moderate', 'Moderate'), ('expert', 'Expert')], help_text='For plants: Easy / Moderate / Expert', max_length=50)),
                ('sunlight', models.CharField(blank=True, help_text="e.g. 'Bright indirect light', 'Low light'", max_length=100)),
                ('watering', models.CharField(blank=True, help_text="e.g. 'Once a week', 'When top inch is dry'", max_length=100)),
                ('pet_friendly', models.BooleanField(blank=True, help_text='Is this plant safe for pets? (plants only)', null=True)),
                ('air_purifying', models.BooleanField(default=False, help_text='Is this an air-purifying plant?')),
                ('description', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='One highlight per line. e.g:\nPurifies air\nLow maintenance')),
                ('care_instructions', models.TextField(blank=True, help_text='Detailed care guide — one tip per line')),
                ('what_you_get', models.TextField(blank=True, help_text="What's included — one item per line. e.g:\n1 healthy plant\nEco-friendly packaging")),
                ('warranty_info', models.CharField(blank=True, help_text="e.g. '7-day healthy plant guarantee'", max_length=200)),
                ('return_policy', models.CharField(blank=True, help_text="e.g. 'Damaged on arrival? We'll replace it.'", max_length=200)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_best_deal', models.BooleanField(default=False)),
                ('is_featured_home', models.BooleanField(default=False, help_text='Show on homepage hero / featured section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Optional — mainly for planters/care/seeds', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
                ('space_tags', models.ManyToManyField(blank=True, help_text='Which spaces is this plant/planter suited for?', related_name='products', to='store.spacetag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large'), ('25g', '25g'), ('50g', '50g'), ('100g', '100g'), ('250g', '250g'), ('250ml', '250ml'), ('500ml', '500ml'), ('1l', '1 Litre'), ('standard', 'Standard'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], default='standard', help_text='Size of this variant', max_length=50)),
                ('color', models.CharField(blank=True, help_text="Color name e.g. 'Terracotta', 'Sage Green', 'White Ceramic'", max_length=100)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color code e.g. #E07B54 — shown as color swatch on frontend', max_length=7)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra amount added to base price. 0 = same as base price.', max_digits=10)),
                ('sku_suffix', models.CharField(blank=True, help_text='Optional variant-level SKU suffix e.g. -SM-TER', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['size', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Link this image to a specific variant (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='store.productvariant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('variant_info', models.CharField(blank=True, help_text="e.g. 'Medium / Terracotta Pot'", max_length=200)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchAndShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='YouTube/Vimeo embed URL or direct video URL')),
                ('thumbnail', models.ImageField(help_text='Thumbnail shown before video plays (also shown in cart if linked)', upload_to='watch_shop/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, help_text="Link to a product for 'Shop Now' button", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_videos', to='store.product')),
            ],
            options={
                'verbose_name': 'Watch & Shop Video',
                'verbose_name_plural': 'Watch & Shop Videos',
                'ordering': ['order'],
            },
        ),
    ]
