# Generated by Django 5.2.13 on 2026-05-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('title', models.CharField(blank=True, help_text="Overlay text e.g. 'Self Watering Pots'", max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, help_text='Internal link e.g. /shop?collection=self-watering', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide (Navbar Banner)',
                'verbose_name_plural': 'Hero Slides (Navbar Banner)',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured_home',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_info',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku_suffix',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_estimate',
            field=models.CharField(blank=True, default='3-5 business days', help_text="e.g. '3-5 business days', 'Same day in Hyderabad'", max_length=100),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Lucide icon name e.g. 'leaf', 'flower', 'sprout'", max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy Care'), ('moderate', 'Moderate'), ('expert', 'Expert')], help_text='For plants only: Easy / Moderate / Expert', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_deal',
            field=models.BooleanField(default=False, help_text='✅ Tick this to show product in Golden Deals / Offers section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pet_friendly',
            field=models.BooleanField(blank=True, help_text='Is this plant safe for pets?', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='what_you_get',
            field=models.TextField(blank=True, help_text="What's included — one item per line.\ne.g:\n1 healthy plant\nEco-friendly packaging\nCare card"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark one image as the primary/featured image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order — lower = shown first'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, help_text="Color name e.g. 'Terracotta', 'Sage Green'. Leave blank if no color variant.", max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Hex code e.g. #E07B54 — shown as color swatch on frontend', max_length=7),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra ₹ added to base price for this variant. Enter 0 for no change.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large'), ('25g', '25g'), ('50g', '50g'), ('100g', '100g'), ('250g', '250g'), ('250ml', '250ml'), ('500ml', '500ml'), ('1l', '1 Litre'), ('standard', 'Standard'), ('s', 'S'), ('m', 'M'), ('l', 'L')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this review in the Testimonials section on homepage'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=999.0, help_text='Order value above which shipping is free', max_digits=10),
        ),
        migrations.AlterField(
            model_name='watchandshop',
            name='product',
            field=models.ForeignKey(blank=True, help_text="Link to a product — shows 'Shop Now' button", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_videos', to='store.product'),
        ),
        migrations.AlterField(
            model_name='watchandshop',
            name='thumbnail',
            field=models.ImageField(help_text='Thumbnail shown before video plays', upload_to='watch_shop/'),
        ),
        migrations.AlterField(
            model_name='watchandshop',
            name='video_url',
            field=models.URLField(help_text='YouTube embed URL e.g. https://www.youtube.com/embed/xxxxx'),
        ),
    ]
