# Generated by Django 5.2.13 on 2026-05-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_faq_heroslide_remove_product_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Color name shown on website e.g. 'Terracotta', 'Sage Green'", max_length=100, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Hex color code e.g. #E07B54 — shown as color swatch on product page', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Color Option',
                'verbose_name_plural': 'Color Options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Size label shown on website e.g. 'Small', '250ml', 'Standard'", max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in dropdowns and on product page')),
            ],
            options={
                'verbose_name': 'Size Option',
                'verbose_name_plural': 'Size Options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size__order', 'color__order']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_estimate',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_hex',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='(Optional) Link this image to a specific variant. When that variant is selected, this image shows first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='store.productvariant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='air_purifying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Care guide — one tip per line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy Care'), ('moderate', 'Moderate'), ('expert', 'Expert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_deal',
            field=models.BooleanField(default=False, help_text='✅ Tick to show in Golden Deals / Offers section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pet_friendly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='space_tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.spacetag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sunlight',
            field=models.CharField(blank=True, help_text="e.g. 'Bright indirect light'", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='watering',
            field=models.CharField(blank=True, help_text="e.g. 'Once a week'", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='what_you_get',
            field=models.TextField(blank=True, help_text="What's included — one item per line\ne.g.:\n1 healthy plant\nEco-friendly packaging\nCare card"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark one image as the main/featured image for the product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order — lower number = shown first'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra ₹ added to base price. Enter 0 for no change.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage testimonials section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(default='919XXXXXXXXXX', help_text='Include country code, no + e.g. 919876543210', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchandshop',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_videos', to='store.product'),
        ),
        migrations.AlterField(
            model_name='watchandshop',
            name='thumbnail',
            field=models.ImageField(upload_to='watch_shop/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, help_text="Pick a color — leave blank if no color variant. Add new colors in 'Color Options' panel", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='store.coloroption'),
        ),
        migrations.CreateModel(
            name='DeliveryEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text="e.g. 'Within Telangana', 'Other States', 'North East India'", max_length=100)),
                ('estimate', models.CharField(help_text="e.g. '3-5 business days', 'Same day'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_estimates', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(help_text="Pick a size — add new sizes in 'Size Options' panel", on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='store.sizeoption'),
        ),
    ]
