# Generated by Django 5.2.13 on 2026-05-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_coloroption_sizeoption_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='(Optional) Which color does this image belong to? When the customer selects this color, these images will be shown first. Leave blank for images that apply to all colors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='store.coloroption'),
        ),
        migrations.AlterField(
            model_name='coloroption',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Hex color code e.g. #E07B54 — shown as swatch on product page', max_length=7),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, help_text="Pick a color — leave blank if no color variant. Add colors in 'Color Options' panel", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='store.coloroption'),
        ),
    ]
