# Generated by Django 5.2.13 on 2026-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productimage_variant_productimage_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='growth_rate',
            field=models.CharField(blank=True, choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], help_text='How fast the plant grows — shown in care guide', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='temperature',
            field=models.CharField(blank=True, help_text="Ideal temperature range e.g. '18°C – 30°C' — shown in care guide", max_length=100),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='show_in_navbar',
            field=models.BooleanField(default=True, help_text="Show this size in the 'Shop by Size' section of the navbar"),
        ),
        migrations.AlterField(
            model_name='coloroption',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Hex color code e.g. #E07B54 — shown as color dot on product page', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text="Detailed care guide — one tip per line. Shown in 'Care Guide' tab on product page."),
        ),
        migrations.AlterField(
            model_name='sizeoption',
            name='name',
            field=models.CharField(help_text="Size label shown on website e.g. 'Small', '250ml', 'Standard'", max_length=100, unique=True),
        ),
    ]
