# Generated by Django 5.2.13 on 2026-05-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_growth_rate_product_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title',
        ),
    ]
