# Generated by Django 5.2.13 on 2026-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_heroslide_subtitle_remove_heroslide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, help_text="Overlay text e.g. 'Self Watering Pots'", max_length=200),
        ),
    ]
