# Generated by Django 5.2.13 on 2026-05-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_heroslide_subtitle_heroslide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchandshop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Featured image. Multiple images can be marked as primary.'),
        ),
    ]
