# Generated by Django 5.2.13 on 2026-05-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exchange Request', 'verbose_name_plural': 'Exchange Requests'},
        ),
        migrations.AlterField(
            model_name='exchangecode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted_return_policy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='request_type',
            field=models.CharField(choices=[('Exchange', 'Exchange (Defective product replacement)')], default='Exchange', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField()),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved — Return Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed — Refund Processed')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('refund_initiated', models.BooleanField(default=False)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_return_requests', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Return Request',
                'verbose_name_plural': 'Order Return Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
