# Generated by Django 5.2.13 on 2026-05-13 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_returnrequest_options_alter_exchangecode_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreturnrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_applied',
            field=models.BooleanField(default=False, help_text='True once coupon uses_count has been incremented. Never set manually.'),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_consumed',
            field=models.BooleanField(default=False, help_text='True once exchange code has been marked used. Never set manually.'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(db_index=True, default=False, help_text='True once stock has been deducted after payment. Never set manually.'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False, help_text='True once stock has been restored (cancellation/return). Never set manually.'),
        ),
        migrations.AddField(
            model_name='orderreturnrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreturnrequest',
            name='stock_restored',
            field=models.BooleanField(default=False, help_text='True once stock has been restored for this return. Never set manually.'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangecode',
            name='code',
            field=models.CharField(help_text='Auto-generated unique code given to customer', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted_return_policy',
            field=models.BooleanField(default=True, help_text='Customer accepted 15-day exchange policy at checkout'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_label',
            field=models.CharField(blank=True, help_text="e.g. 'Medium / Sage Green'", max_length=200),
        ),
        migrations.AlterField(
            model_name='orderreturnrequest',
            name='reason',
            field=models.TextField(help_text='Reason for return'),
        ),
        migrations.AlterField(
            model_name='orderreturnrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderreturnrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderreturnrequest',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video evidence', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin response visible to customer'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='defect_description',
            field=models.TextField(help_text='Customer describes the product defect in detail'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='defect_video_url',
            field=models.URLField(blank=True, help_text='Link to defect video (YouTube, Google Drive, etc.)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='request_type',
            field=models.CharField(default='Exchange', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
