# Generated by Django 5.2.13 on 2026-05-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderreturnrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'verbose_name': 'Exchange Request', 'verbose_name_plural': 'Exchange Requests'},
        ),
    ]
